build:
    image: default-bionic
    environment:
        php: 8.1.2
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            general:
                linefeed_character: return-newline
            around_operators:
                concatenation: true   
tools:
    external_code_coverage: true                 
