build:
    image: default-bionic
    environment:
        php: 8.1.2
    dependencies:
        override:
            - composer install --ignore-platform-reqs --no-interaction        
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
filter:
    excluded_paths:
        - 'tests/*'
    paths:
        - src/
    dependency_paths:
        - vendor/        
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            general:
                linefeed_character: return-newline
            around_operators:
                concatenation: true    
tools:
    external_code_coverage: true                 
